cc_binary(
    name = "crtp_example",
    srcs = ["crtp_example.cc"],
    copts = ["--std=c++17"]
)

cc_binary(
    name = "crtp_example_polymorphism",
    srcs = ["crtp_example_polymorphism.cc"],
    copts = ["--std=c++17"]
)